# Generated by Django 3.0.5 on 2020-04-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckrent',
            name='pickup_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
