# Generated by Django 3.0.5 on 2020-04-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_truck_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckrent',
            name='client_drop_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='truckrent',
            name='client_required_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
