# Generated by Django 3.0.5 on 2020-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_auto_20200428_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckrent',
            name='client_drop_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='truckrent',
            name='client_required_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='truckrent',
            name='drop_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='truckrent',
            name='pickup_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
