# Generated by Django 3.0.5 on 2020-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_auto_20200430_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckrent',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
